name: Test Studio Agent
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Appel de l'Agent Studio
        uses: nadescheemaeker/ai-core@main
        with:
          api_key: ${{ secrets.AZURE_API_KEY }}
          api_base: "https://mon-studio-ai.openai.azure.com/"
          agent_type: "reviewer"
          model_name: "azure/gpt4o"
