name: Test Studio Agent
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Appel de l'Agent Studio
        uses: nadescheemaeker/ai-core@main
        with:
          api_key: ${{ secrets.GOOGLE_API_KEY }}
          agent_type: "reviewer"
          model_name: "gemini/gemini-1.5-pro-latest"
